import '../styles/tokens.css';
import './button/Button';
import './card/Card';
import './footer/Footer';
import './header/Header';
import './image/Image';
import './text/Text';
import './section/Section';
import '../pages/Home/Home';